### PR TITLE
Updates for non-twbt to align with 47.01 release

### PR DESCRIPTION
**Pull request by janxious**
Chose tiles for altar and die that are maybe not most correct.

Altar: 
image

Die:
image

### CODE REVIEW

**Comment by claireanlage** [comment]
Looks reasonable. If there's interest to use different tiles in the future, it can always be changed later.
I'm not familiar with the TWBT compatibility files, but it seems to be all correct.
I'll leave the release creation to @jecowa

**Comment by claireanlage** [comment]
Sorry, didn't mean to reject.
Also reminder for @jecowa to update manifest.json with the new version before making a release

**Comment by janxious** [comment]
Thanks @claireanlage !

**Comment by jecowa** [comment]
That looks like a good tile for altars. I'm not sure about what's best for dice. I was considering tile 42 for dice. Need to do some testing sometime to see how dice look. I think they might be doing something fancy with them.

**Comment by janxious** [comment]
42 was my second choice 👍. I haven't seen them in-game yet!

**Pull request merged**
